In [1]:
'''
Author: Bryan Bo Cao
Email: boca7588@colorado.edu or bo.cao-1@colorado.edu
Github Repo: https://github.com/BryanBo-Cao/neuralnets-deeplearning
'''
from __future__ import print_function

import tensorflow as tf
import numpy as np
import random
import copy
import matplotlib.pyplot as plt

# Reading data
all_output_0_train_accuracy = 0.787670391748
all_output_0_test_accuracy = 0.789889253486
all_output_1_train_accuracy = 0.212329608252
all_output_1_test_accuracy = 0.210110746514

train_data = np.genfromtxt('train_data.txt', delimiter=',')
#print "train_data:", train_data

t = train_data[:,2]
hu = train_data[:,3]
lt = train_data[:,4]
co2 = train_data[:,5]
hu_r = train_data[:,6]

o = train_data[:,7]

#data
data = np.column_stack((t, hu, lt, co2, hu_r))
data = np.float32(data)
#print ("data:", data)

#print "np.shape(train_data): ", np.shape(train_data)
#print "np.shape(t): ", np.shape(t)
'''
print ("t: ", t)
print ("hu: ", hu)
print ("lt: ", lt)
print ("co2: ", co2)
print ("hu_r: ", hu_r)
print ("o: ", o)
'''
x_data = np.array(data)
y_data = np.array(o)
print ([x_data, y_data])

[array([[  2.31800003e+01,   2.72719994e+01,   4.26000000e+02,
          7.21250000e+02,   4.79298830e-03],
       [  2.31499996e+01,   2.72674999e+01,   4.29500000e+02,
          7.14000000e+02,   4.78344085e-03],
       [  2.31499996e+01,   2.72450008e+01,   4.26000000e+02,
          7.13500000e+02,   4.77946363e-03],
       ..., 
       [  2.11000004e+01,   3.60950012e+01,   4.33000000e+02,
          7.98500000e+02,   5.59563888e-03],
       [  2.11000004e+01,   3.62599983e+01,   4.33000000e+02,
          8.20333313e+02,   5.62144956e-03],
       [  2.11000004e+01,   3.62000008e+01,   4.47000000e+02,
          8.21000000e+02,   5.61206369e-03]], dtype=float32), array([ 1.,  1.,  1., ...,  1.,  1.,  1.])]


In [2]:
def normalize(data):
    #normalize train data
    #normalize t
    t = data[:, 0]
    t_min = np.min(t)
    t_max = np.max(t)
    d_t = t_max - t_min
    #normalized t: n_t
    n_t = []
    for each in t:
        n_t.append((each - t_min) / d_t)

    #normalize hu
    hu = data[:, 1]
    hu_min = np.min(hu)
    hu_max = np.max(hu)
    d_hu = hu_max - hu_min
    #normalized h: n_hu
    n_hu = []
    for each in hu:
        n_hu.append((each - hu_min) / d_hu)

    #normalize lt
    lt = data[:, 2]
    lt_min = np.min(lt)
    lt_max = np.max(lt)
    d_lt = lt_max - lt_min
    #normalized lt: n_lt
    n_lt = []
    for each in lt:
        n_lt.append((each - lt_min) / d_lt)

    #normalize co2
    co2 = data[:, 3]
    co2_min = np.min(co2)
    co2_max = np.max(co2)
    d_co2 = co2_max - co2_min
    #normalized co2: n_co2
    n_co2 = []
    for each in co2:
        n_co2.append((each - co2_min) / d_co2)

    #normalize hu_r
    hu_r = data[:, 4]
    hu_r_min = np.min(hu_r)
    hu_r_max = np.max(hu_r)
    d_hu_r = hu_r_max - hu_r_min
    #normalized hu_r: n_hu_r
    n_hu_r = []
    for each in hu_r:
        n_hu_r.append((each - hu_r_min) / d_hu_r)

    #normalized data: n_data
    n_data = np.column_stack((n_t, n_hu, n_lt, n_co2, n_hu_r))

    return n_data

n_data = normalize(data)
print ("n_data:", n_data)
x_data = np.array(n_data)
y_data = np.array(o)
print ([x_data, y_data])

n_data: [[ 1.          0.47053295  0.2754904   0.190933    0.55731839]
 [ 0.99282283  0.47033185  0.27775383  0.18644592  0.55480719]
 [ 0.99282283  0.4693262   0.2754904   0.18613647  0.55376107]
 ..., 
 [ 0.50239241  0.86490113  0.28001723  0.23874362  0.76843745]
 [ 0.50239241  0.87227613  0.28001723  0.25225642  0.77522635]
 [ 0.50239241  0.8695944   0.2890709   0.25266904  0.77275759]]
[array([[ 1.        ,  0.47053295,  0.2754904 ,  0.190933  ,  0.55731839],
       [ 0.99282283,  0.47033185,  0.27775383,  0.18644592,  0.55480719],
       [ 0.99282283,  0.4693262 ,  0.2754904 ,  0.18613647,  0.55376107],
       ..., 
       [ 0.50239241,  0.86490113,  0.28001723,  0.23874362,  0.76843745],
       [ 0.50239241,  0.87227613,  0.28001723,  0.25225642,  0.77522635],
       [ 0.50239241,  0.8695944 ,  0.2890709 ,  0.25266904,  0.77275759]], dtype=float32), array([ 1.,  1.,  1., ...,  1.,  1.,  1.])]


In [3]:
def get_normalized_test_data(test_data):
    test_t = test_data[:,2]
    test_hu = test_data[:,3]
    test_lt = test_data[:,4]
    test_co2 = test_data[:,5]
    test_hu_r = test_data[:,6]

    new_test_data = np.column_stack((test_t, test_hu, test_lt, test_co2, test_hu_r))
    # print "new_test_data:", new_test_data

    #normalize test data
    return normalize(new_test_data)
test_data = np.genfromtxt('test_data.txt', delimiter=',')
o_test = test_data[:, 7]
n_test_data = get_normalized_test_data(test_data)
print ("n_test_data:", n_test_data)
print ("o_test:", o_test)

n_test_data: [[ 0.46216769  0.52556469  0.27661817  0.34237253  0.70022289]
 [ 0.46830266  0.51800397  0.27661817  0.32373573  0.69523877]
 [ 0.46370143  0.52495038  0.2745098   0.32609151  0.70044674]
 ..., 
 [ 0.28425358  0.33342784  0.26786844  0.65134541  0.38577152]
 [ 0.28425358  0.3491636   0.26486401  0.72076222  0.40288059]
 [ 0.30674847  0.35355826  0.25869703  0.86650613  0.41941993]]
o_test: [ 1.  1.  1. ...,  1.  1.  1.]


In [4]:
n_input = 5
H0 = 2
n_output = 1
output_num_nodes = 1
lr = 0.05
epochs = 1000
bs = 100
data_size = len(x_data)

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

ws0 = tf.Variable(tf.random_uniform([n_input, H0], -1.0, 1.0))
ws1 = tf.Variable(tf.random_uniform([H0, n_output], -1.0, 1.0))

H0_outputs = tf.sigmoid(tf.matmul(X, ws0))
#H0_outputs = tf.matmul(X, ws0)
hy = tf.sigmoid(tf.matmul(H0_outputs, ws1))
#hy = tf.matmul(H0_outputs, ws1)

#cost = tf.reduce_mean(tf.square(Y - hy))
cost = tf.reduce_mean(tf.square(Y - hy) / 2)
#cost = tf.reduce_mean(tf.nn.l2_loss(Y - hy))
'''
x_data_batch, y_data_batch = tf.train.batch(
    [x_data, y_data],
    batch_size = bs)
'''
x_data_batch = tf.train.batch([x_data], batch_size = bs)
y_data_batch = tf.train.batch([y_data], batch_size = bs)

optimizer = tf.train.GradientDescentOptimizer(lr).minimize(cost)

init = tf.global_variables_initializer()

print ("x_data_batch: ", x_data_batch)
print ("y_data_batch: ", y_data_batch)
print ("x_data_batch[0]: ", x_data_batch[0])
print ("tf.cast(x_data_batch[0][0][0], 'float'): ", tf.cast(x_data_batch[0][0][0], "float"))

x_data_batch:  Tensor("batch:0", shape=(100, 8143, 5), dtype=float32)
y_data_batch:  Tensor("batch_1:0", shape=(100, 8143), dtype=float64)
x_data_batch[0]:  Tensor("strided_slice:0", shape=(8143, 5), dtype=float32)
tf.cast(x_data_batch[0][0][0], 'float'):  Tensor("strided_slice_3:0", shape=(), dtype=float32)


In [5]:
#print (x_data)
print (x_data.shape)
xx_data = x_data[0:100]
print (xx_data.shape)

(8143, 5)
(100, 5)


In [9]:
test_accuracy = 0

with tf.Session() as sess:
    sess.run(init)
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord)
   
    for step in xrange(epochs):
        
        #train network in batch size = bs
        bs_i = 0
        while bs_i <= data_size:
            batch_end = 0
            
            if bs_i + 100 < data_size:
                batch_end = bs_i + 100
            else:
                batch_end = data_size
            xx_data_batch = x_data[bs_i : batch_end]
            yy_data_batch = y_data[bs_i : batch_end]
            
            sess.run(optimizer, feed_dict={X: xx_data_batch, Y: yy_data_batch})
            bs_i += 100
        
        #sess.run(optimizer, feed_dict={X: xx_data_batch, Y: yy_data_batch})
        
        if step % 50 == 0:
            print ("   ")
            print ("Step:", step)
            print ("Cost:", sess.run(cost, feed_dict={X: x_data, Y: y_data}))
            correct_prediction = tf.equal(tf.floor(hy + 0.5), Y)
            test_accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
            test_accuracy = test_accuracy.eval({X: n_test_data, Y: o_test})
            print ("test_accuracy: ", test_accuracy)
            
    correct_prediction = tf.equal(tf.floor(hy + 0.5), Y)
    test_accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    test_accuracy = test_accuracy.eval({X: n_test_data, Y: o_test})
    print ("test_accuracy: ", test_accuracy)

   
Step: 0
Cost: 0.121299
test_accuracy:  0.705655
   
Step: 50
Cost: 0.0746971
test_accuracy:  0.705655
   
Step: 100
Cost: 0.0807115
test_accuracy:  0.705655
   
Step: 150
Cost: 0.0854286
test_accuracy:  0.705655
   
Step: 200
Cost: 0.0866221
test_accuracy:  0.705655
   
Step: 250
Cost: 0.0881099
test_accuracy:  0.705655
   
Step: 300
Cost: 0.0890687
test_accuracy:  0.705655
   
Step: 350
Cost: 0.0908799
test_accuracy:  0.705655
   
Step: 400
Cost: 0.093394
test_accuracy:  0.705655
   
Step: 450
Cost: 0.0946313
test_accuracy:  0.705655
   
Step: 500
Cost: 0.0953459
test_accuracy:  0.705655
   
Step: 550
Cost: 0.0963305
test_accuracy:  0.705655
   
Step: 600
Cost: 0.0973448
test_accuracy:  0.705655
   
Step: 650
Cost: 0.0980814
test_accuracy:  0.705655
   
Step: 700
Cost: 0.0985755
test_accuracy:  0.705655
   
Step: 750
Cost: 0.0991845
test_accuracy:  0.705655
   
Step: 800
Cost: 0.100273
test_accuracy:  0.705655
   
Step: 850
Cost: 0.10064
test_accuracy:  0.705655
   
Step: 900
Cost