In [59]:
import numpy as np
import random

train_data = np.genfromtxt('../data/assign2_train_data.txt', delimiter=',')
#print "train_data:", train_data

t = train_data[:,2]
hu = train_data[:,3]
lt = train_data[:,4]
co2 = train_data[:,5]
hu_r = train_data[:,6]

o = train_data[:,7]

#data
data = np.column_stack((t, hu, lt, co2, hu_r))
print "data:", data

print "np.shape(train_data): ", np.shape(train_data)
#print "np.shape(t): ", np.shape(t)

print "t: ", t
print "hu: ", hu
print "lt: ", lt
print "co2: ", co2
print "hu_r: ", hu_r
print "o: ", o

data: [[  2.31800000e+01   2.72720000e+01   4.26000000e+02   7.21250000e+02
    4.79298818e-03]
 [  2.31500000e+01   2.72675000e+01   4.29500000e+02   7.14000000e+02
    4.78344095e-03]
 [  2.31500000e+01   2.72450000e+01   4.26000000e+02   7.13500000e+02
    4.77946352e-03]
 ..., 
 [  2.11000000e+01   3.60950000e+01   4.33000000e+02   7.98500000e+02
    5.59563902e-03]
 [  2.11000000e+01   3.62600000e+01   4.33000000e+02   8.20333333e+02
    5.62144937e-03]
 [  2.11000000e+01   3.62000000e+01   4.47000000e+02   8.21000000e+02
    5.61206354e-03]]
np.shape(train_data):  (8143, 8)
t:  [ 23.18  23.15  23.15 ...,  21.1   21.1   21.1 ]
hu:  [ 27.272   27.2675  27.245  ...,  36.095   36.26    36.2   ]
lt:  [ 426.   429.5  426.  ...,  433.   433.   447. ]
co2:  [ 721.25        714.          713.5        ...,  798.5         820.33333333
  821.        ]
hu_r:  [ 0.00479299  0.00478344  0.00477946 ...,  0.00559564  0.00562145
  0.00561206]
o:  [ 1.  1.  1. ...,  1.  1.  1.]


In [60]:
#normalize inputs

#normalize t
t_min = np.min(t)
t_max = np.max(t)
d_t = t_max - t_min
#normalized t: n_t
n_t = []
for each in t:
    n_t.append((each - t_min) / d_t)

#normalize hu
hu_min = np.min(hu)
hu_max = np.max(hu)
d_hu = hu_max - hu_min
#normalized h: n_hu
n_hu = []
for each in hu:
    n_hu.append((each - hu_min) / d_hu)

#normalize lt
lt_min = np.min(lt)
lt_max = np.max(lt)
d_lt = lt_max - lt_min
#normalized lt: n_lt
n_lt = []
for each in lt:
    n_lt.append((each - lt_min) / d_lt)

#normalize co2
co2_min = np.min(co2)
co2_max = np.max(co2)
d_co2 = co2_max - co2_min
#normalized co2: n_co2
n_co2 = []
for each in co2:
    n_co2.append((each - co2_min) / d_co2)

#normalize hu_r
hu_r_min = np.min(hu_r)
hu_r_max = np.max(hu_r)
d_hu_r = hu_r_max - hu_r_min
#normalized hu_r: n_hu_r
n_hu_r = []
for each in hu_r:
    n_hu_r.append((each - hu_r_min) / d_hu_r)
    
#normalized data: n_data
n_data = np.column_stack((n_t, n_hu, n_lt, n_co2, n_hu_r))
print "n_data:", n_data

n_data: [[ 1.          0.47053302  0.27549041  0.190933    0.55731842]
 [ 0.99282297  0.47033188  0.27775383  0.18644592  0.55480723]
 [ 0.99282297  0.46932618  0.27549041  0.18613647  0.55376106]
 ..., 
 [ 0.50239234  0.86490111  0.28001725  0.23874362  0.76843752]
 [ 0.50239234  0.87227623  0.28001725  0.25225643  0.77522635]
 [ 0.50239234  0.86959437  0.28907092  0.25266904  0.77275762]]


In [61]:
def initialize_weights():
    w_t = random.random()
    w_hu = random.random()
    w_lt = random.random()
    w_co2 = random.random()
    w_hu_r = random.random()
    b = random.random()

    #weights
    ws = [w_t, w_hu, w_lt, w_co2, w_hu_r, b]
    return ws

ws = initialize_weights()
print "ws: ", ws

ws:  [0.2652590412732072, 0.9402782070231802, 0.07155471783377487, 0.31451503494097655, 0.36015880670712586, 0.12481358400852471]


In [96]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def activation(x): # use sigmoid as activation function
    a = sigmoid(x)
    if a >= 0.5:
        return 1
    else:
        return 0

def perceptron(ins, ws):
    sum = 0
    for x, w in zip(ins, ws):
        sum += x * w
    return activation(sum)

# lr - learning rate
# bs - batch size
def train(n_data, lr, bs):
    print "Training starts: len of data:", len(n_data)
    
    accuracies = []
    epoch = 0
    while epoch <= 25000:
        # train
        i = 0
        for (n_t_i, n_hu_i, n_lt_i, n_co2_i, n_hu_r_i, o_i) in zip(n_t, n_hu, n_lt, n_co2, n_hu_r, o):
            sum_error_w_t = 0
            sum_error_w_hu = 0
            sum_error_w_lt = 0
            sum_error_w_co2 = 0
            sum_error_w_hu_r = 0
            sum_error_b = 0
            
            error = o_i - (n_t_i * ws[0] + n_hu_i * ws[1] + n_lt_i * ws[2] + n_co2_i * ws[3] + n_hu_r_i * ws[4] + ws[5])
            sum_error_w_t += error * n_t_i
            sum_error_w_hu += error * n_hu_i
            sum_error_w_lt += error * n_lt_i
            sum_error_w_co2 += error * n_co2_i
            sum_error_w_hu_r += error * n_hu_r_i
            sum_error_b += error
            
            if i >= bs: # only update weights after one batch size
                ws[0] += lr * sum_error_w_t
                ws[1] += lr * sum_error_w_hu
                ws[2] += lr * sum_error_w_lt
                ws[3] += lr * sum_error_w_co2
                ws[4] += lr * sum_error_w_hu_r
                ws[5] += lr * sum_error_b
                sum_error_w_t = 0
                sum_error_w_hu = 0
                sum_error_w_lt = 0
                sum_error_w_co2 = 0
                sum_error_w_hu_r = 0
                sum_error_b = 0
                i = 1
                continue
            
            #test every epoch
            accuracy = get_one_feedforward_accuracy(n_data, ws, o)
            accuracies.append(accuracy)
            print "epoch:", epoch, " accuracy:",accuracy
            
            i += 1
        
        # count 
        epoch += 1
    print "Training ends."
        
def get_one_feedforward_accuracy(n_data, ws, o):
    
    #calculate accuracy
    #outputs
    os = []
    for each in zip(n_data):
        for ins in each:
            os.append(perceptron(ins, ws))
            
    #count correct output number
    correct_cnt = 0
    for o_i, os_i in zip(o, os):
        if (o_i == os_i):
            correct_cnt += 1
    accuracy = float(correct_cnt) / float(len(o))
    ##calculate accuracy
    return accuracy
    

In [97]:
train(n_data, lr = 0.0001, bs = 1)

Training starts: len of data: 8143
epoch: 0  accuracy: 0.610217364608
epoch: 1  accuracy: 0.610217364608
epoch: 2  accuracy: 0.610217364608
epoch: 3  accuracy: 0.610462974334
epoch: 4  accuracy: 0.610585779197
epoch: 5  accuracy: 0.610585779197
epoch: 6  accuracy: 0.610462974334
epoch: 7  accuracy: 0.610585779197
epoch: 8  accuracy: 0.610462974334
epoch: 9  accuracy: 0.610462974334
epoch: 10  accuracy: 0.610340169471
epoch: 11  accuracy: 0.610217364608
epoch: 12  accuracy: 0.610340169471
epoch: 13  accuracy: 0.610585779197
epoch: 14  accuracy: 0.61070858406
epoch: 15  accuracy: 0.61070858406
epoch: 16  accuracy: 0.61070858406
epoch: 17  accuracy: 0.610831388923
epoch: 18  accuracy: 0.610954193786
epoch: 19  accuracy: 0.610831388923
epoch: 20  accuracy: 0.610585779197
epoch: 21  accuracy: 0.61070858406
epoch: 22  accuracy: 0.610954193786
epoch: 23  accuracy: 0.610831388923
epoch: 24  accuracy: 0.610831388923
epoch: 25  accuracy: 0.610831388923
epoch: 26  accuracy: 0.610954193786
epoch: 

KeyboardInterrupt: 